package com.portal.job.pojo;
// Generated Feb 23, 2016 11:56:10 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BRole generated by hbm2java
 */
@Entity
@Table(name="b_role"
    ,catalog="portal"
)
public class BRole  implements java.io.Serializable {


     private BRoleId id;
     private String roleName;

    public BRole() {
    }

    public BRole(BRoleId id, String roleName) {
       this.id = id;
       this.roleName = roleName;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="roleId", column=@Column(name="ROLE_ID", nullable=false, length=45) ) } )
    public BRoleId getId() {
        return this.id;
    }
    
    public void setId(BRoleId id) {
        this.id = id;
    }

    
    @Column(name="ROLE_NAME", nullable=false, length=45)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }




}


