package com.portal.job.pojo;
// Generated Feb 23, 2016 11:56:10 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * BRoleId generated by hbm2java
 */
@Embeddable
public class BRoleId  implements java.io.Serializable {


     private int id;
     private String roleId;

    public BRoleId() {
    }

    public BRoleId(int id, String roleId) {
       this.id = id;
       this.roleId = roleId;
    }
   


    @Column(name="ID", nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="ROLE_ID", nullable=false, length=45)
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BRoleId) ) return false;
		 BRoleId castOther = ( BRoleId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getRoleId()==castOther.getRoleId()) || ( this.getRoleId()!=null && castOther.getRoleId()!=null && this.getRoleId().equals(castOther.getRoleId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getRoleId() == null ? 0 : this.getRoleId().hashCode() );
         return result;
   }   


}


