package com.portal.job.pojo;
// Generated Feb 23, 2016 11:56:10 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BTestQues generated by hbm2java
 */
@Entity
@Table(name="b_test_ques"
    ,catalog="portal"
)
public class BTestQues  implements java.io.Serializable {


     private Integer id;
     private String quesName;
     private String optionA;
     private String optionB;
     private String optionC;
     private String optionD;
     private String answer;

    public BTestQues() {
    }

    public BTestQues(String quesName, String optionA, String optionB, String optionC, String optionD, String answer) {
       this.quesName = quesName;
       this.optionA = optionA;
       this.optionB = optionB;
       this.optionC = optionC;
       this.optionD = optionD;
       this.answer = answer;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
@Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="QUES_NAME", nullable=false)
    public String getQuesName() {
        return this.quesName;
    }
    
    public void setQuesName(String quesName) {
        this.quesName = quesName;
    }

    
    @Column(name="OPTION_A", nullable=false)
    public String getOptionA() {
        return this.optionA;
    }
    
    public void setOptionA(String optionA) {
        this.optionA = optionA;
    }

    
    @Column(name="OPTION_B", nullable=false)
    public String getOptionB() {
        return this.optionB;
    }
    
    public void setOptionB(String optionB) {
        this.optionB = optionB;
    }

    
    @Column(name="OPTION_C", nullable=false)
    public String getOptionC() {
        return this.optionC;
    }
    
    public void setOptionC(String optionC) {
        this.optionC = optionC;
    }

    
    @Column(name="OPTION_D", nullable=false)
    public String getOptionD() {
        return this.optionD;
    }
    
    public void setOptionD(String optionD) {
        this.optionD = optionD;
    }

    
    @Column(name="ANSWER", nullable=false, length=1)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


