package com.portal.job.pojo;
// Generated Feb 23, 2016 11:56:10 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Userdetails generated by hbm2java
 */
@Entity
@Table(name="userdetails"
    ,catalog="portal"
)
public class Userdetails  implements java.io.Serializable {


     private UserdetailsId id;
     private String password;
     private String firstName;
     private String lastName;
     private String dateOfBirth;
     private String email;
     private Integer addressId;
     private int roleId;
     private String testStatus;
     private String mobileNo;
    public Userdetails() {
    }

	
    public Userdetails(UserdetailsId id, String password, String firstName, String dateOfBirth, String email, int roleId, String testStatus) {
        this.id = id;
        this.password = password;
        this.firstName = firstName;
        this.dateOfBirth = dateOfBirth;
        this.email = email;
        this.roleId = roleId;
        this.testStatus = testStatus;
    }
    public Userdetails(UserdetailsId id, String password, String firstName, String lastName, String dateOfBirth, String email, Integer addressId, int roleId, String testStatus) {
       this.id = id;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.dateOfBirth = dateOfBirth;
       this.email = email;
       this.addressId = addressId;
       this.roleId = roleId;
       this.testStatus = testStatus;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="ID", nullable=false) ), 
        @AttributeOverride(name="userName", column=@Column(name="USER_NAME", nullable=false, length=45) ) } )
    public UserdetailsId getId() {
        return this.id;
    }
    
    public void setId(UserdetailsId id) {
        this.id = id;
    }

    
    @Column(name="PASSWORD", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="FIRST_NAME", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="DATE_OF_BIRTH", nullable=false, length=45)
    public String getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="EMAIL", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="ADDRESS_ID")
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    
    @Column(name="ROLE_ID", nullable=false)
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="TEST_STATUS", nullable=false, length=1,columnDefinition = "varchar(1) default `N`")
    public String getTestStatus() {
        return this.testStatus;
    }
    
    public void setTestStatus(String testStatus) {
        this.testStatus = testStatus;
    }

    @Column(name = "MOBILE_NO", nullable = false)
    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }




}


