package com.portal.job.pojo;
// Generated Feb 23, 2016 11:56:10 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;


/**
 * UserdetailsId generated by hbm2java
 */
@Embeddable
public class UserdetailsId  implements java.io.Serializable {


     private int id;
     private String userName;

    public UserdetailsId() {
    }

    public UserdetailsId(int id, String userName) {
       this.id = id;
       this.userName = userName;
    }
   


    @Column(name="ID", nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="USER_NAME", nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserdetailsId) ) return false;
		 UserdetailsId castOther = ( UserdetailsId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         return result;
   }   


}


