package com.portal.job.pojo;
// Generated Feb 23, 2016 11:56:10 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserTest generated by hbm2java
 */
@Entity
@Table(name="user_test"
    ,catalog="portal"
)
public class UserTest  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private int testQuesId;
     private String listOfQues;

    public UserTest() {
    }

	
    public UserTest(int userId, int testQuesId) {
        this.userId = userId;
        this.testQuesId = testQuesId;
    }
    public UserTest(int userId, int testQuesId, String listOfQues) {
       this.userId = userId;
       this.testQuesId = testQuesId;
       this.listOfQues = listOfQues;
    }
   
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="USER_ID", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="TEST_QUES_ID", nullable=false)
    public int getTestQuesId() {
        return this.testQuesId;
    }
    
    public void setTestQuesId(int testQuesId) {
        this.testQuesId = testQuesId;
    }

    
    @Column(name="LIST_OF_QUES", length=65535)
    public String getListOfQues() {
        return this.listOfQues;
    }
    
    public void setListOfQues(String listOfQues) {
        this.listOfQues = listOfQues;
    }




}


